-- Creating teachers role
CREATE ROLE teachers WITH NOLOGIN;
CREATE ROLE james WITH PASSWORD 'hello' LOGIN IN ROLE teachers;
CREATE ROLE rileydrizzy WITH PASSWORD 'ladi' LOGIN SUPERUSER;
CREATE ROLE lucas WITH LOGIN PASSWORD 'xxx' VALID UNTIL '2030-12-25 23:59:59';
CREATE ROLE ladipo WITH LOGIN PASSWORD 'ladi' IN ROLE teachers;
GRANT teachers TO james WITH ADMIN OPTION;
ALTER ROLE james SUPERUSER;
--